apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  # docs: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-redis-pubsub/
  # (for SB: https://docs.dapr.io/reference/components-reference/supported-pubsub/setup-azure-servicebus-queues/)
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: concurrency
    value: 1
  - name: redeliverInterval
    value: 10s
