# @name startWorkflow
POST http://localhost:8100/workflows
Content-Type: application/json

{"test": "test value"}

###

GET http://localhost:8100/workflows/{{startWorkflow.response.body.instance_id}}
