# @name startWorkflow
POST http://localhost:8100/workflows
Content-Type: application/json

[
	{
		"action": "processor1",
		"content" : "Hello World"
	}
]

###

GET http://localhost:8100/workflows/{{startWorkflow.response.body.instance_id}}
