# @name startSimpleWorkflow
POST http://localhost:8100/workflows
Content-Type: application/json

[
	{
		"action": "processor1",
		"content" : "Hello World"
	}
]

###
GET http://localhost:8100/workflows/{{startSimpleWorkflow.response.body.instance_id}}


###

# @name startMultiStepWorkflow
POST http://localhost:8100/workflows
Content-Type: application/json

[
	{
		"action": "processor1",
		"content" : "Hello World"
	},
	{
		"action": "processor1",
		"content" : "Do stuff"
	},
	{
		"action": "processor1",
		"content" : "Do more stuff"
	}
]

###
GET http://localhost:8100/workflows/{{startMultiStepWorkflow.response.body.instance_id}}


