apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  features:
    - name: Resiliency
      enabled: true

  appHttpPipeline:
    handlers:
    - name: ratelimit
      type: middleware.http.ratelimit

  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"