apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: throttling-resiliency
scopes:
  - sender
  - workflow1
spec:
  policies:
    # Retries are named templates for retry configurations and are instantiated for life of the operation.
    retries:
      retry1:
        # policy: constant
        # duration: 7s
        # maxRetries: 2
        policy: exponential
        maxInterval: 5m
        maxRetries: 2

  # targets:
  #   apps:
  #     processor1:
  #       retry: retry1
  #     # processor2:
  #     #   retry: retry1

